stages:
  - build

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE:latest
  DOCKER_TLS_CERTDIR: ""

build-and-push:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  only:
    - main
